# Individual Report \- ACS Housing and Economics

by Johannes Kaendler

\(Because the social data is not available for all states, I wiil just focus on the other two\)

In [1]:
import pandas as pd
import numpy as np

In [2]:
housing = pd.read_csv("./data/ACSDP1Y2022.DP04-Data.csv", low_memory=False)
economics = pd.read_csv("./data/ACSDP1Y2022.DP03-Data.csv", low_memory=False)
confirmed = pd.read_csv("../Team/covid_confirmed_usafacts.csv")
deaths = pd.read_csv("../Team/covid_deaths_usafacts.csv")
county_population = pd.read_csv("../Team/covid_county_population_usafacts.csv")
housing_labels = pd.read_csv("data/ACSDP1Y2022.DP03-Column-Metadata.csv")
economics_labels = pd.read_csv("data/ACSDP1Y2022.DP04-Column-Metadata.csv")

Let's calculate the COVID\-19 data trends of the last week. We will build the final dataset based on the population dataset. Since the data is in absolute number, we will first calculate the change from two weeks ago to last week. Then we subtract that from the difference of this week and last week

In [3]:
THIS_WEEK = '2023-07-23'
LAST_WEEK = '2023-07-16'
TWO_WEEKS_AGO = '2023-07-09'
df = county_population.copy()
df['confirmed-trend'] = ((confirmed[THIS_WEEK]-confirmed[THIS_WEEK])-(confirmed[LAST_WEEK]-confirmed[TWO_WEEKS_AGO]))
df['death-trend'] = ((deaths[THIS_WEEK]-deaths[THIS_WEEK])-(deaths[LAST_WEEK]-deaths[TWO_WEEKS_AGO]))
print(f" On average thet number of new cases in the last week was {df['confirmed-trend'].mean()} more than the week before. The biggest reduction is {df['confirmed-trend'].min()}. The highest increase was {df['confirmed-trend'].max()}")
print(f" On average thet number of new deaths in the last week was {df['death-trend'].mean()} more than the week before. The biggest reduction is {df['death-trend'].min()}. The highest increase was {df['death-trend'].max()}")
df.head()

 On average thet number of new cases in the last week was -6.271218290009395 more than the week before. The biggest reduction is -2814.0. The highest increase was 636.0
 On average thet number of new deaths in the last week was -0.043532727842154714 more than the week before. The biggest reduction is -13.0. The highest increase was 2.0

,countyFIPS,County Name,State,population,confirmed-trend,death-trend
0,0,Statewide Unallocated,AL,0,0.0,0.0
1,1001,Autauga County,AL,55869,0.0,0.0
2,1003,Baldwin County,AL,223234,0.0,0.0
3,1005,Barbour County,AL,24686,0.0,0.0
4,1007,Bibb County,AL,22394,0.0,0.0

It is safe to say that the number of deaths was stable increasing decreasing by only \-13 to \+2

The number of new confirmed case is not stable and different for each county. This sugest that COVID is still spreading, but more localized.

In [4]:
housing = pd.read_csv("./data/ACSDP1Y2022.DP04-Data.csv", low_memory=False)
economics = pd.read_csv("./data/ACSDP1Y2022.DP03-Data.csv", low_memory=False)
housing_labels = pd.read_csv("data/ACSDP1Y2022.DP03-Column-Metadata.csv")
economics_labels = pd.read_csv("data/ACSDP1Y2022.DP04-Column-Metadata.csv")

In [5]:
housing.head()

,GEO_ID,NAME,DP04_0001E,DP04_0001M,DP04_0001MA,DP04_0001EA,DP04_0002E,DP04_0002EA,DP04_0002M,DP04_0002MA,...,DP04_0141PMA,DP04_0142PE,DP04_0142PEA,DP04_0142PM,DP04_0142PMA,DP04_0143PE,DP04_0143PEA,DP04_0143PM,DP04_0143PMA,Unnamed: 1146
0,Geography,Geographic Area Name,Estimate!!HOUSING OCCUPANCY!!Total housing units,Margin of Error!!HOUSING OCCUPANCY!!Total hous...,Annotation of Margin of Error!!HOUSING OCCUPAN...,Annotation of Estimate!!HOUSING OCCUPANCY!!Tot...,Estimate!!HOUSING OCCUPANCY!!Total housing uni...,Annotation of Estimate!!HOUSING OCCUPANCY!!Tot...,Margin of Error!!HOUSING OCCUPANCY!!Total hous...,Annotation of Margin of Error!!HOUSING OCCUPAN...,...,Annotation of Percent Margin of Error!!GROSS R...,Percent!!GROSS RENT AS A PERCENTAGE OF HOUSEHO...,Annotation of Percent!!GROSS RENT AS A PERCENT...,Percent Margin of Error!!GROSS RENT AS A PERCE...,Annotation of Percent Margin of Error!!GROSS R...,Percent!!GROSS RENT AS A PERCENTAGE OF HOUSEHO...,Annotation of Percent!!GROSS RENT AS A PERCENT...,Percent Margin of Error!!GROSS RENT AS A PERCE...,Annotation of Percent Margin of Error!!GROSS R...,NaN
1,0500000US01003,"Baldwin County, Alabama",132299,185,NaN,NaN,98854,NaN,3781,NaN,...,NaN,46.3,NaN,9.2,NaN,(X),(X),(X),(X),NaN
2,0500000US01015,"Calhoun County, Alabama",53408,87,NaN,NaN,45701,NaN,1562,NaN,...,NaN,34.9,NaN,8.8,NaN,(X),(X),(X),(X),NaN
3,0500000US01043,"Cullman County, Alabama",39893,40,NaN,NaN,35966,NaN,1274,NaN,...,NaN,39.7,NaN,14.3,NaN,(X),(X),(X),(X),NaN
4,0500000US01049,"DeKalb County, Alabama",31022,39,NaN,NaN,26459,NaN,1114,NaN,...,NaN,32.4,NaN,12.6,NaN,(X),(X),(X),(X),NaN

In [6]:
economics.head()

,GEO_ID,NAME,DP03_0001E,DP03_0001M,DP03_0001MA,DP03_0001EA,DP03_0002E,DP03_0002M,DP03_0002MA,DP03_0002EA,...,DP03_0135PMA,DP03_0136PE,DP03_0136PEA,DP03_0136PM,DP03_0136PMA,DP03_0137PE,DP03_0137PM,DP03_0137PMA,DP03_0137PEA,Unnamed: 1098
0,Geography,Geographic Area Name,Estimate!!EMPLOYMENT STATUS!!Population 16 yea...,Margin of Error!!EMPLOYMENT STATUS!!Population...,Annotation of Margin of Error!!EMPLOYMENT STAT...,Annotation of Estimate!!EMPLOYMENT STATUS!!Pop...,Estimate!!EMPLOYMENT STATUS!!Population 16 yea...,Margin of Error!!EMPLOYMENT STATUS!!Population...,Annotation of Margin of Error!!EMPLOYMENT STAT...,Annotation of Estimate!!EMPLOYMENT STATUS!!Pop...,...,Annotation of Percent Margin of Error!!PERCENT...,Percent!!PERCENTAGE OF FAMILIES AND PEOPLE WHO...,Annotation of Percent!!PERCENTAGE OF FAMILIES ...,Percent Margin of Error!!PERCENTAGE OF FAMILIE...,Annotation of Percent Margin of Error!!PERCENT...,Percent!!PERCENTAGE OF FAMILIES AND PEOPLE WHO...,Percent Margin of Error!!PERCENTAGE OF FAMILIE...,Annotation of Percent Margin of Error!!PERCENT...,Annotation of Percent!!PERCENTAGE OF FAMILIES ...,NaN
1,0500000US01003,"Baldwin County, Alabama",201504,1225,NaN,NaN,117259,3370,NaN,NaN,...,NaN,11.0,NaN,2.5,NaN,25.9,5.3,NaN,NaN,NaN
2,0500000US01015,"Calhoun County, Alabama",94762,667,NaN,NaN,53438,2853,NaN,NaN,...,NaN,14.5,NaN,3.6,NaN,33.2,5.9,NaN,NaN,NaN
3,0500000US01043,"Cullman County, Alabama",72822,501,NaN,NaN,43353,2012,NaN,NaN,...,NaN,15.1,NaN,3.9,NaN,31.9,7.4,NaN,NaN,NaN
4,0500000US01049,"DeKalb County, Alabama",56340,610,NaN,NaN,32603,1753,NaN,NaN,...,NaN,15.9,NaN,4.8,NaN,38.3,6.4,NaN,NaN,NaN

Let's edit the eky column so that all match

In [7]:
housing['GEO_ID'] = pd.to_numeric(housing['GEO_ID'].str.slice(start=9))
economics['GEO_ID'] = pd.to_numeric(economics['GEO_ID'].str.slice(start=9))
df['countyFIPS'] = pd.to_numeric(df['countyFIPS'])

Now we can merge the data sets

In [8]:
df = df.merge(economics, left_on='countyFIPS', right_on='GEO_ID').merge(housing, left_on='countyFIPS', right_on='GEO_ID')

Let's write the data to a csv

In [9]:
df.to_csv("merged_set.csv")
df.head()

,countyFIPS,County Name,State,population,confirmed-trend,death-trend,GEO_ID_x,NAME_x,DP03_0001E,DP03_0001M,...,DP04_0141PMA,DP04_0142PE,DP04_0142PEA,DP04_0142PM,DP04_0142PMA,DP04_0143PE,DP04_0143PEA,DP04_0143PM,DP04_0143PMA,Unnamed: 1146
0,1003,Baldwin County,AL,223234,0.0,0.0,1003.0,"Baldwin County, Alabama",201504,1225,...,NaN,46.3,NaN,9.2,NaN,(X),(X),(X),(X),NaN
1,1015,Calhoun County,AL,113605,0.0,0.0,1015.0,"Calhoun County, Alabama",94762,667,...,NaN,34.9,NaN,8.8,NaN,(X),(X),(X),(X),NaN
2,1043,Cullman County,AL,83768,0.0,0.0,1043.0,"Cullman County, Alabama",72822,501,...,NaN,39.7,NaN,14.3,NaN,(X),(X),(X),(X),NaN
3,1049,DeKalb County,AL,71513,0.0,0.0,1049.0,"DeKalb County, Alabama",56340,610,...,NaN,32.4,NaN,12.6,NaN,(X),(X),(X),(X),NaN
4,1051,Elmore County,AL,81209,0.0,0.0,1051.0,"Elmore County, Alabama",72804,524,...,NaN,26.5,NaN,9.9,NaN,(X),(X),(X),(X),NaN